name: beta_rec
channels:
  - defaults
dependencies:
  - _pytorch_select=0.1=cpu_0
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1=py37_0
  - cffi=1.14.0=py37hb5b8e2f_0
  - intel-openmp=2019.4=233
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37hfbe908c_0
  - mkl_fft=1.0.15=py37h5e564d8_0
  - mkl_random=1.1.0=py37ha771720_0
  - mock=4.0.1=py_0
  - ncurses=6.2=h0a44026_0
  - ninja=1.9.0=py37h04f5b5a_0
  - numpy=1.18.1=py37h7241aed_0
  - numpy-base=1.18.1=py37h6575580_1
  - openssl=1.1.1f=h1de35cc_0
  - pip=20.0.2=py37_1
  - psutil=5.7.0=py37h1de35cc_0
  - pycparser=2.20=py_0
  - python=3.7.7=hc70fcce_0_cpython
  - pytorch=1.4.0=cpu_py37hf9bb1df_0
  - readline=8.0=h1de35cc_0
  - setuptools=46.1.3=py37_0
  - six=1.14.0=py37_0
  - sqlite=3.31.1=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - wheel=0.34.2=py37_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - absl-py==0.9.0
    - aiohttp==3.6.2
    - appdirs==1.4.3
    - appnope==0.1.0
    - async-timeout==3.0.1
    - attrs==19.3.0
    - backcall==0.1.0
    - beautifulsoup4==4.9.0
    - black==19.10b0
    - cachetools==4.0.0
    - chardet==3.0.4
    - click==7.1.1
    - colorama==0.4.3
    - cycler==0.10.0
    - decorator==4.4.2
    - entrypoints==0.3
    - filelock==3.0.12
    - flake8==3.7.9
    - google==2.0.3
    - google-auth==1.13.1
    - google-auth-oauthlib==0.4.1
    - gputil==1.4.0
    - grpcio==1.28.1
    - idna==2.9
    - importlib-metadata==1.6.0
    - ipython==7.13.0
    - ipython-genutils==0.2.0
    - jedi==0.16.0
    - joblib==0.14.1
    - jsonschema==3.2.0
    - kiwisolver==1.2.0
    - livelossplot==0.5.0
    - markdown==3.2.1
    - matplotlib==3.2.1
    - mccabe==0.6.1
    - more-itertools==8.2.0
    - multidict==4.7.5
    - oauthlib==3.1.0
    - packaging==20.3
    - pandas==1.0.3
    - parso==0.6.2
    - pathspec==0.7.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pluggy==0.13.1
    - prometheus-client==0.7.1
    - prompt-toolkit==3.0.5
    - protobuf==3.11.3
    - ptyprocess==0.6.0
    - py==1.8.1
    - py-cpuinfo==5.0.0
    - py-spy==0.3.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.5.0
    - pyflakes==2.1.1
    - pygments==2.6.1
    - pyparsing==2.4.7
    - pyrsistent==0.16.0
    - pytest==5.4.1
    - python-dateutil==2.8.1
    - pytz==2019.3
    - pyyaml==5.3.1
    - ray==0.8.4
    - redis==3.4.1
    - regex==2020.4.4
    - requests==2.23.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - scikit-learn==0.22.2.post1
    - scipy==1.4.1
    - soupsieve==2.0
    - tabulate==0.8.7
    - tensorboard==2.2.0
    - tensorboard-plugin-wit==1.6.0.post3
    - tensorboardx==2.0
    - toml==0.10.0
    - tqdm==4.45.0
    - traitlets==4.3.3
    - typed-ast==1.4.1
    - urllib3==1.25.8
    - wcwidth==0.1.9
    - werkzeug==1.0.1
    - yarl==1.4.2
    - zipp==3.1.0
prefix: /Users/mzq/anaconda3/envs/beta_rec

